# configs/trainer/default.yaml

epochs: 1000
project_name: "vdl"
save_dir: "models"
run_name: "default_run"

sample_images_every: 50
ema_decay: 0.995

batch_size: 16

diffusion:
  noise_steps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  img_size: 64
  device: ${device}

scheduler:
  _target_: torch.optim.lr_scheduler.CosineAnnealingLR
  T_max: ${trainer.epochs}
